#!/usr/bin/env bash
#
# Render every provider preset in deploy/provider/ into a committed, apply-able
# manifest in deploy/static/provider/.
#
#   deploy/render.sh            regenerate them
#   deploy/render.sh --check    fail if the committed files are stale
#
# # Why commit generated files at all
#
# So that installing needs no Helm. `kubectl apply -f deploy/static/provider/aws.yaml`
# is one command against one file, which is what a cluster with a locked-down
# toolchain, an Argo CD application, or a person reading a runbook at 3am can
# actually use. The cost is that they can go stale, which --check exists to
# catch: run it in CI and a chart change that nobody re-rendered fails the build
# instead of shipping a manifest that no longer matches the chart it claims to
# come from.
#
# # Determinism
#
# The output must depend on nothing but the chart and the values — no
# timestamps, no version stamps, no hostname, or --check would fail on every
# machine that is not the one that last ran it. `helm template` is already
# deterministic; this script adds only fixed text.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CHART="$REPO_ROOT/deploy/chart/ramjet-ingress"
PROVIDER_DIR="$REPO_ROOT/deploy/provider"
STATIC_DIR="$REPO_ROOT/deploy/static/provider"

# Baked in rather than passed: these names appear inside the rendered objects
# (as the release-qualified object name and the namespace of every namespaced
# one), so changing them changes the file. A flag here would be a way to
# generate manifests that --check then rejects.
RELEASE="ramjet"
NAMESPACE="ramjet-ingress"

CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

command -v helm >/dev/null || { echo "helm is required" >&2; exit 1; }

# The Namespace the rest of the objects live in. The chart does not template one
# — Helm creates it with --create-namespace — but a static manifest has no such
# step, and an apply that fails halfway because the namespace is missing is a
# bad first experience.
namespace_object() {
  cat <<YAML
apiVersion: v1
kind: Namespace
metadata:
  name: $NAMESPACE
  labels:
    app.kubernetes.io/name: ramjet-ingress
    app.kubernetes.io/instance: $RELEASE
YAML
}

header() {
  local provider="$1"
  cat <<EOF
# ramjet-ingress — $provider
#
# Generated. Do not edit this file: edit deploy/provider/$provider/values.yaml
# and re-run deploy/render.sh, or every change here is lost the next time
# anyone does.
#
#     kubectl apply -f deploy/static/provider/$provider.yaml
#
# Equivalent to:
#
#     helm install $RELEASE deploy/chart/ramjet-ingress \\
#       --namespace $NAMESPACE --create-namespace \\
#       -f deploy/provider/$provider/values.yaml
#
# The values file carries the reasoning behind each annotation below; this file
# deliberately carries none of it, because a comment here has nowhere to live
# across a re-render. Read deploy/README.md and the preset before deploying.
---
EOF
}

render_one() {
  local provider="$1"
  header "$provider"
  namespace_object
  echo "---"
  helm template "$RELEASE" "$CHART" \
    --namespace "$NAMESPACE" \
    --values "$PROVIDER_DIR/$provider/values.yaml"
}

providers=()
for dir in "$PROVIDER_DIR"/*/; do
  [[ -f "$dir/values.yaml" ]] || continue
  providers+=("$(basename "$dir")")
done
# Sorted, so the set of files rendered does not depend on the order the
# filesystem happens to hand back.
IFS=$'\n' providers=($(sort <<<"${providers[*]}")); unset IFS

(( ${#providers[@]} > 0 )) || { echo "no presets found under $PROVIDER_DIR" >&2; exit 1; }

mkdir -p "$STATIC_DIR"

drift=()
for provider in "${providers[@]}"; do
  target="$STATIC_DIR/$provider.yaml"
  rendered="$(render_one "$provider")"

  if (( CHECK )); then
    if [[ ! -f "$target" ]]; then
      drift+=("$provider (missing $target)")
    elif ! diff -q <(printf '%s\n' "$rendered") "$target" >/dev/null; then
      drift+=("$provider")
      printf '\033[31m--- drift in %s ---\033[0m\n' "$provider" >&2
      diff -u "$target" <(printf '%s\n' "$rendered") | head -40 >&2 || true
    fi
  else
    printf '%s\n' "$rendered" >"$target"
    printf '  rendered %s\n' "${target#"$REPO_ROOT"/}"
  fi
done

# A file in static/ with no preset behind it is a preset someone deleted and a
# manifest nobody will ever regenerate — worth failing on rather than leaving to
# rot.
for existing in "$STATIC_DIR"/*.yaml; do
  [[ -e "$existing" ]] || continue
  name="$(basename "$existing" .yaml)"
  if [[ ! -f "$PROVIDER_DIR/$name/values.yaml" ]]; then
    if (( CHECK )); then
      drift+=("$name (orphaned $existing, no preset)")
    else
      rm -f "$existing"
      printf '  removed orphaned %s\n' "${existing#"$REPO_ROOT"/}"
    fi
  fi
done

if (( CHECK )); then
  if (( ${#drift[@]} )); then
    printf '\n\033[31m%d manifest(s) out of date:\033[0m\n' "${#drift[@]}" >&2
    printf '  %s\n' "${drift[@]}" >&2
    printf '\nRun deploy/render.sh and commit the result.\n' >&2
    exit 1
  fi
  printf 'all %d manifests match the chart\n' "${#providers[@]}"
else
  printf '\n%d manifests written to %s\n' "${#providers[@]}" "${STATIC_DIR#"$REPO_ROOT"/}"
fi
